### ISSUE TITLE
ros2 cli or dev tools with zenoh bridge

### ISSUE THREAD

**Issue by harishkumarb-tw** [evshary/autoware_carla_launch#25]
I am new to zenoh dds bridge. When my autoware is running, I couldn't see topics or nodes using ros2 cli. I get empty output when I run `ros2 node list` or `ros2 topic list`. 
I did exec into the humble docker container and ran `ros2 topic list` while the autoware is running in another terminal(same container),
<img width="361" alt="Screenshot 2023-08-04 at 2 57 24 PM" src="https://github.com/evshary/autoware_carla_launch/assets/81152683/ad65a82d-93e7-4590-8c01-9986d88ae29f">
What am I missing? How to use all the ros2 dev tools(cli, rqt, rosbag, etc) using the zenoh bridge(for carla data)?

**Comment by evshary** [comment]
Do you run `source env.sh` before `ros2 topic list`?
Since there are some environment settings about ROS in `env.sh`, I guess it'll affect the ros2 cli tools
https://github.com/evshary/autoware_carla_launch/blob/humble/env.sh#L16

**Comment by harishkumarb-tw** [comment]
Thanks for the quick reply. It works now after sourcing 👍. 
But, is there anyway to bridge the carla data/topics alone without running the whole `autoware.launch`?

**Comment by evshary** [comment]
zenoh-bridge-dds has two modes: mirror and forward. I use mirror mode here, which is the default.
Only forward mode supports commands like `ros2 topic list`, but the performance might be worse.
I don't use the mode because I've already known all the topics I need, but maybe it is worth giving it a try.
For more detail, you can check here.
https://github.com/eclipse-zenoh/zenoh-plugin-dds#full-support-of-ros-graph-and-topic-lists-via-the-forward-discovery-mode

Another way is to create a dummy ROS node that subscribes to the topic you need, then zenoh-bridge-dds would be able to bridge the data/topics for them.

**Comment by datvuthanh** [comment]
Hi @harishkumarb-tw , i ran this script source env.sh but it didn't work. Could you give me some suggestions?

**Comment by evshary** [comment]
> Hi @harishkumarb-tw , i ran this script source env.sh but it didn't work. Could you give me some suggestions?

Do you mean `ros2 topic list` not work? If so, try `ros2 daemon stop` and then try again. (remember to source env.sh)
It would be great if you provide more detailed information.

**Comment by datvuthanh** [comment]
hi @evshary , this didnt work for me. 
![Screenshot from 2023-10-31 14-32-09](https://github.com/evshary/autoware_carla_launch/assets/44630913/e20910f4-2437-4310-8ac4-fe98a8e7b40e)

**Comment by evshary** [comment]
@datvuthanh You need to run `ros2 topic list` in the same container.
I think you can use terminal multiplexer like tmux to run Autoware and ros2 command at the same time.

**Comment by datvuthanh** [comment]
@evshary thank you, it works now.

**Comment by evshary** [comment]
Close the issue while it's completed
